# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DashboardUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardForm(object):
    def setupUi(self, DashboardForm):
        DashboardForm.setObjectName("DashboardForm")
        DashboardForm.resize(1304, 779)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Resources/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DashboardForm.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DashboardForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 35, 45, 255), stop:1 rgba(69, 83, 100, 255));\n"
"color: rgb(255, 255, 255);\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setContentsMargins(11, 3, 11, 11)
        self.main_layout.setSpacing(7)
        self.main_layout.setObjectName("main_layout")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_header.sizePolicy().hasHeightForWidth())
        self.frame_header.setSizePolicy(sizePolicy)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggle_broadcast = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_broadcast.sizePolicy().hasHeightForWidth())
        self.toggle_broadcast.setSizePolicy(sizePolicy)
        self.toggle_broadcast.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.toggle_broadcast.setFont(font)
        self.toggle_broadcast.setCheckable(True)
        self.toggle_broadcast.setChecked(False)
        self.toggle_broadcast.setObjectName("toggle_broadcast")
        self.horizontalLayout.addWidget(self.toggle_broadcast)
        self.remote_spy = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remote_spy.sizePolicy().hasHeightForWidth())
        self.remote_spy.setSizePolicy(sizePolicy)
        self.remote_spy.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remote_spy.setFont(font)
        self.remote_spy.setCheckable(True)
        self.remote_spy.setObjectName("remote_spy")
        self.horizontalLayout.addWidget(self.remote_spy)
        self.remote_command = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remote_command.sizePolicy().hasHeightForWidth())
        self.remote_command.setSizePolicy(sizePolicy)
        self.remote_command.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remote_command.setFont(font)
        self.remote_command.setObjectName("remote_command")
        self.horizontalLayout.addWidget(self.remote_command)
        self.file_share = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_share.sizePolicy().hasHeightForWidth())
        self.file_share.setSizePolicy(sizePolicy)
        self.file_share.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_share.setFont(font)
        self.file_share.setObjectName("file_share")
        self.horizontalLayout.addWidget(self.file_share)
        self.main_layout.addWidget(self.frame_header)
        self.frame_body = QtWidgets.QFrame(self.centralwidget)
        self.frame_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_body)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName("splitter")
        self.desktop_widget_container = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desktop_widget_container.sizePolicy().hasHeightForWidth())
        self.desktop_widget_container.setSizePolicy(sizePolicy)
        self.desktop_widget_container.setObjectName("desktop_widget_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.desktop_widget_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.desktop_layout = QtWidgets.QListWidget(self.desktop_widget_container)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.desktop_layout.setFont(font)
        self.desktop_layout.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.desktop_layout.setProperty("showDropIndicator", False)
        self.desktop_layout.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.desktop_layout.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.desktop_layout.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.desktop_layout.setIconSize(QtCore.QSize(240, 135))
        self.desktop_layout.setMovement(QtWidgets.QListView.Free)
        self.desktop_layout.setResizeMode(QtWidgets.QListView.Adjust)
        self.desktop_layout.setViewMode(QtWidgets.QListView.IconMode)
        self.desktop_layout.setObjectName("desktop_layout")
        self.verticalLayout_2.addWidget(self.desktop_layout)
        self.log_widget_container = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_widget_container.sizePolicy().hasHeightForWidth())
        self.log_widget_container.setSizePolicy(sizePolicy)
        self.log_widget_container.setObjectName("log_widget_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.log_widget_container)
        self.verticalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.log_area = QtWidgets.QTextBrowser(self.log_widget_container)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.log_area.setFont(font)
        self.log_area.setReadOnly(True)
        self.log_area.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.log_area.setOpenLinks(False)
        self.log_area.setObjectName("log_area")
        self.verticalLayout_3.addWidget(self.log_area)
        self.action_buttons_layout_2 = QtWidgets.QHBoxLayout()
        self.action_buttons_layout_2.setObjectName("action_buttons_layout_2")
        self.file_receive_config = QtWidgets.QPushButton(self.log_widget_container)
        self.file_receive_config.setObjectName("file_receive_config")
        self.action_buttons_layout_2.addWidget(self.file_receive_config)
        self.client_quit = QtWidgets.QPushButton(self.log_widget_container)
        self.client_quit.setObjectName("client_quit")
        self.action_buttons_layout_2.addWidget(self.client_quit)
        self.verticalLayout_3.addLayout(self.action_buttons_layout_2)
        self.action_buttons_layout_1 = QtWidgets.QHBoxLayout()
        self.action_buttons_layout_1.setObjectName("action_buttons_layout_1")
        self.send_message_button = QtWidgets.QPushButton(self.log_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_message_button.sizePolicy().hasHeightForWidth())
        self.send_message_button.setSizePolicy(sizePolicy)
        self.send_message_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.send_message_button.setObjectName("send_message_button")
        self.action_buttons_layout_1.addWidget(self.send_message_button)
        self.clear_log_area = QtWidgets.QPushButton(self.log_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_log_area.sizePolicy().hasHeightForWidth())
        self.clear_log_area.setSizePolicy(sizePolicy)
        self.clear_log_area.setObjectName("clear_log_area")
        self.action_buttons_layout_1.addWidget(self.clear_log_area)
        self.verticalLayout_3.addLayout(self.action_buttons_layout_1)
        self.verticalLayout_4.addWidget(self.splitter)
        self.main_layout.addWidget(self.frame_body)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 30)
        self.verticalLayout.addLayout(self.main_layout)
        DashboardForm.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(DashboardForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setBaseSize(QtCore.QSize(0, 0))
        self.toolBar.setWindowTitle("toolBar")
        self.toolBar.setStyleSheet("height: 20px")
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolBar.setObjectName("toolBar")
        DashboardForm.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.client_sort = QtWidgets.QAction(DashboardForm)
        self.client_sort.setObjectName("client_sort")
        self.client_select_all = QtWidgets.QAction(DashboardForm)
        self.client_select_all.setObjectName("client_select_all")
        self.client_scroll_in = QtWidgets.QAction(DashboardForm)
        self.client_scroll_in.setObjectName("client_scroll_in")
        self.client_scroll_out = QtWidgets.QAction(DashboardForm)
        self.client_scroll_out.setObjectName("client_scroll_out")
        self.client_rename = QtWidgets.QAction(DashboardForm)
        self.client_rename.setObjectName("client_rename")
        self.about = QtWidgets.QAction(DashboardForm)
        self.about.setObjectName("about")
        self.toolBar.addAction(self.client_sort)
        self.toolBar.addAction(self.client_select_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.client_rename)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.client_scroll_in)
        self.toolBar.addAction(self.client_scroll_out)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.about)

        self.retranslateUi(DashboardForm)
        self.client_select_all.triggered.connect(self.desktop_layout.selectAll)
        self.client_sort.triggered.connect(self.desktop_layout.doItemsLayout)
        self.client_scroll_in.triggered.connect(DashboardForm.client_scroll_in)
        self.client_scroll_out.triggered.connect(DashboardForm.client_scroll_out)
        self.send_message_button.clicked.connect(DashboardForm.send_message)
        self.toggle_broadcast.clicked['bool'].connect(DashboardForm.toggle_broadcast)
        self.remote_command.clicked.connect(DashboardForm.remote_command)
        self.remote_spy.clicked['bool'].connect(DashboardForm.toggle_remote_spy)
        self.client_rename.triggered.connect(DashboardForm.client_rename)
        self.about.triggered.connect(DashboardForm.show_about)
        self.file_receive_config.clicked.connect(DashboardForm.show_file_receive)
        self.client_quit.clicked.connect(DashboardForm.client_quit)
        self.clear_log_area.clicked.connect(self.log_area.clear)
        self.log_area.anchorClicked['QUrl'].connect(DashboardForm.show_file_receive)
        self.file_share.clicked.connect(DashboardForm.show_file_server)
        QtCore.QMetaObject.connectSlotsByName(DashboardForm)

    def retranslateUi(self, DashboardForm):
        _translate = QtCore.QCoreApplication.translate
        DashboardForm.setWindowTitle(_translate("DashboardForm", "PYCM Dashboard"))
        self.label.setText(_translate("DashboardForm", "Python Classroom Management System"))
        self.toggle_broadcast.setText(_translate("DashboardForm", "Screen Broadcast"))
        self.remote_spy.setText(_translate("DashboardForm", "Remote View"))
        self.remote_command.setText(_translate("DashboardForm", "Remote Command"))
        self.file_share.setText(_translate("DashboardForm", "File Share"))
        self.file_receive_config.setText(_translate("DashboardForm", "File Receive"))
        self.client_quit.setText(_translate("DashboardForm", "Quit Client"))
        self.send_message_button.setText(_translate("DashboardForm", "Messaging"))
        self.clear_log_area.setText(_translate("DashboardForm", "Clear Log"))
        self.client_sort.setText(_translate("DashboardForm", "Arrange Client"))
        self.client_select_all.setText(_translate("DashboardForm", "Select All"))
        self.client_scroll_in.setText(_translate("DashboardForm", "Zoom In"))
        self.client_scroll_out.setText(_translate("DashboardForm", "Zoom Out"))
        self.client_rename.setText(_translate("DashboardForm", "Rename"))
        self.about.setText(_translate("DashboardForm", "About"))
import Resources_rc
