# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DashboardUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardForm(object):
    def setupUi(self, DashboardForm):
        DashboardForm.setObjectName("DashboardForm")
        DashboardForm.resize(1155, 771)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/UI/Resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DashboardForm.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DashboardForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(5)
        self.main_layout.setObjectName("main_layout")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.frame_header)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toggle_broadcast = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_broadcast.sizePolicy().hasHeightForWidth())
        self.toggle_broadcast.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.toggle_broadcast.setFont(font)
        self.toggle_broadcast.setCheckable(True)
        self.toggle_broadcast.setChecked(False)
        self.toggle_broadcast.setObjectName("toggle_broadcast")
        self.horizontalLayout_2.addWidget(self.toggle_broadcast)
        self.remote_spy = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remote_spy.sizePolicy().hasHeightForWidth())
        self.remote_spy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.remote_spy.setFont(font)
        self.remote_spy.setObjectName("remote_spy")
        self.horizontalLayout_2.addWidget(self.remote_spy)
        self.file_transfer = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_transfer.sizePolicy().hasHeightForWidth())
        self.file_transfer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.file_transfer.setFont(font)
        self.file_transfer.setObjectName("file_transfer")
        self.horizontalLayout_2.addWidget(self.file_transfer)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.status_widget_container = QtWidgets.QWidget(self.frame_header)
        self.status_widget_container.setObjectName("status_widget_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.status_widget_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.file_transfer_status = QtWidgets.QLabel(self.status_widget_container)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.file_transfer_status.setFont(font)
        self.file_transfer_status.setAlignment(QtCore.Qt.AlignCenter)
        self.file_transfer_status.setObjectName("file_transfer_status")
        self.gridLayout_3.addWidget(self.file_transfer_status, 1, 0, 1, 1)
        self.network_discover_status = QtWidgets.QLabel(self.status_widget_container)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.network_discover_status.setFont(font)
        self.network_discover_status.setAlignment(QtCore.Qt.AlignCenter)
        self.network_discover_status.setObjectName("network_discover_status")
        self.gridLayout_3.addWidget(self.network_discover_status, 0, 0, 1, 1)
        self.private_message_status = QtWidgets.QLabel(self.status_widget_container)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.private_message_status.setFont(font)
        self.private_message_status.setAlignment(QtCore.Qt.AlignCenter)
        self.private_message_status.setObjectName("private_message_status")
        self.gridLayout_3.addWidget(self.private_message_status, 1, 1, 1, 1)
        self.class_broadcast_status = QtWidgets.QLabel(self.status_widget_container)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.class_broadcast_status.setFont(font)
        self.class_broadcast_status.setAlignment(QtCore.Qt.AlignCenter)
        self.class_broadcast_status.setObjectName("class_broadcast_status")
        self.gridLayout_3.addWidget(self.class_broadcast_status, 0, 1, 1, 1)
        self.screen_broadcast_status = QtWidgets.QLabel(self.status_widget_container)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.screen_broadcast_status.setFont(font)
        self.screen_broadcast_status.setAlignment(QtCore.Qt.AlignCenter)
        self.screen_broadcast_status.setObjectName("screen_broadcast_status")
        self.gridLayout_3.addWidget(self.screen_broadcast_status, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.status_widget_container)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 1)
        self.main_layout.addWidget(self.frame_header)
        self.frame_body = QtWidgets.QFrame(self.centralwidget)
        self.frame_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_body)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.desktop_widget_container = QtWidgets.QWidget(self.frame_body)
        self.desktop_widget_container.setObjectName("desktop_widget_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.desktop_widget_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.desktop_layout = QtWidgets.QListWidget(self.desktop_widget_container)
        self.desktop_layout.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.desktop_layout.setProperty("showDropIndicator", False)
        self.desktop_layout.setDragEnabled(False)
        self.desktop_layout.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.desktop_layout.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.desktop_layout.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.desktop_layout.setIconSize(QtCore.QSize(240, 135))
        self.desktop_layout.setMovement(QtWidgets.QListView.Free)
        self.desktop_layout.setResizeMode(QtWidgets.QListView.Adjust)
        self.desktop_layout.setViewMode(QtWidgets.QListView.IconMode)
        self.desktop_layout.setObjectName("desktop_layout")
        self.verticalLayout_2.addWidget(self.desktop_layout)
        self.horizontalLayout_3.addWidget(self.desktop_widget_container)
        self.log_widget_container = QtWidgets.QWidget(self.frame_body)
        self.log_widget_container.setObjectName("log_widget_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.log_widget_container)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.log_area = QtWidgets.QTextEdit(self.log_widget_container)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.log_area.setFont(font)
        self.log_area.setReadOnly(True)
        self.log_area.setObjectName("log_area")
        self.verticalLayout_3.addWidget(self.log_area)
        self.horizontalLayout_3.addWidget(self.log_widget_container)
        self.horizontalLayout_3.setStretch(0, 8)
        self.horizontalLayout_3.setStretch(1, 2)
        self.main_layout.addWidget(self.frame_body)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 10)
        self.verticalLayout.addLayout(self.main_layout)
        DashboardForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.services_operation_menu = QtWidgets.QMenu(self.menu)
        self.services_operation_menu.setObjectName("services_operation_menu")
        DashboardForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardForm)
        self.statusbar.setObjectName("statusbar")
        DashboardForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(DashboardForm)
        self.toolBar.setObjectName("toolBar")
        DashboardForm.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.client_sort = QtWidgets.QAction(DashboardForm)
        self.client_sort.setObjectName("client_sort")
        self.clear_client_selection = QtWidgets.QAction(DashboardForm)
        self.clear_client_selection.setObjectName("clear_client_selection")
        self.start_all_services_menu = QtWidgets.QAction(DashboardForm)
        self.start_all_services_menu.setObjectName("start_all_services_menu")
        self.stop_all_services_menu = QtWidgets.QAction(DashboardForm)
        self.stop_all_services_menu.setObjectName("stop_all_services_menu")
        self.restart_all_services_menu = QtWidgets.QAction(DashboardForm)
        self.restart_all_services_menu.setObjectName("restart_all_services_menu")
        self.exit_menu = QtWidgets.QAction(DashboardForm)
        self.exit_menu.setObjectName("exit_menu")
        self.client_scroll_in = QtWidgets.QAction(DashboardForm)
        self.client_scroll_in.setObjectName("client_scroll_in")
        self.client_scroll_out = QtWidgets.QAction(DashboardForm)
        self.client_scroll_out.setObjectName("client_scroll_out")
        self.services_operation_menu.addAction(self.start_all_services_menu)
        self.services_operation_menu.addAction(self.stop_all_services_menu)
        self.services_operation_menu.addAction(self.restart_all_services_menu)
        self.menu.addAction(self.services_operation_menu.menuAction())
        self.menu.addAction(self.exit_menu)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.client_sort)
        self.toolBar.addAction(self.clear_client_selection)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.client_scroll_in)
        self.toolBar.addAction(self.client_scroll_out)

        self.retranslateUi(DashboardForm)
        self.clear_client_selection.triggered.connect(DashboardForm.clear_client_selection)
        self.client_sort.triggered.connect(self.desktop_layout.doItemsLayout)
        self.exit_menu.triggered.connect(DashboardForm.close)
        self.client_scroll_in.triggered.connect(DashboardForm.client_scroll_in)
        self.client_scroll_out.triggered.connect(DashboardForm.client_scroll_out)
        QtCore.QMetaObject.connectSlotsByName(DashboardForm)

    def retranslateUi(self, DashboardForm):
        _translate = QtCore.QCoreApplication.translate
        DashboardForm.setWindowTitle(_translate("DashboardForm", "PYCM Dashboard"))
        self.toggle_broadcast.setText(_translate("DashboardForm", "屏幕广播"))
        self.remote_spy.setText(_translate("DashboardForm", "远程监控"))
        self.file_transfer.setText(_translate("DashboardForm", "文件传输"))
        self.pushButton.setText(_translate("DashboardForm", "黑屏/解除"))
        self.file_transfer_status.setText(_translate("DashboardForm", "文件分发"))
        self.network_discover_status.setText(_translate("DashboardForm", "网络发现"))
        self.private_message_status.setText(_translate("DashboardForm", "私信"))
        self.class_broadcast_status.setText(_translate("DashboardForm", "公共组"))
        self.screen_broadcast_status.setText(_translate("DashboardForm", "屏幕广播"))
        self.menu.setTitle(_translate("DashboardForm", "系统"))
        self.services_operation_menu.setTitle(_translate("DashboardForm", "服务"))
        self.toolBar.setWindowTitle(_translate("DashboardForm", "toolBar"))
        self.client_sort.setText(_translate("DashboardForm", "自动排列"))
        self.client_sort.setToolTip(_translate("DashboardForm", "自动排列学生端"))
        self.clear_client_selection.setText(_translate("DashboardForm", "取消选择"))
        self.clear_client_selection.setToolTip(_translate("DashboardForm", "取消选择的学生端"))
        self.start_all_services_menu.setText(_translate("DashboardForm", "启动所有服务"))
        self.stop_all_services_menu.setText(_translate("DashboardForm", "停止所有服务"))
        self.restart_all_services_menu.setText(_translate("DashboardForm", "重启所有服务"))
        self.exit_menu.setText(_translate("DashboardForm", "退出"))
        self.client_scroll_in.setText(_translate("DashboardForm", "放大图标"))
        self.client_scroll_in.setToolTip(_translate("DashboardForm", "放大客户端图标"))
        self.client_scroll_out.setText(_translate("DashboardForm", "缩小图标"))
        self.client_scroll_out.setToolTip(_translate("DashboardForm", "缩小客户端图标"))
import Resources_rc
