# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileServerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileServerForm(object):
    def setupUi(self, FileServerForm):
        FileServerForm.setObjectName("FileServerForm")
        FileServerForm.resize(422, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FileServerForm.sizePolicy().hasHeightForWidth())
        FileServerForm.setSizePolicy(sizePolicy)
        FileServerForm.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FileServerForm.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(FileServerForm)
        self.main_layout.setObjectName("main_layout")
        self.working_folder_layout = QtWidgets.QHBoxLayout()
        self.working_folder_layout.setObjectName("working_folder_layout")
        self.working_folder_label = QtWidgets.QLabel(FileServerForm)
        self.working_folder_label.setObjectName("working_folder_label")
        self.working_folder_layout.addWidget(self.working_folder_label)
        self.working_folder = QtWidgets.QLineEdit(FileServerForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.working_folder.sizePolicy().hasHeightForWidth())
        self.working_folder.setSizePolicy(sizePolicy)
        self.working_folder.setText("")
        self.working_folder.setReadOnly(True)
        self.working_folder.setObjectName("working_folder")
        self.working_folder_layout.addWidget(self.working_folder)
        self.working_folder_change = QtWidgets.QPushButton(FileServerForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.working_folder_change.sizePolicy().hasHeightForWidth())
        self.working_folder_change.setSizePolicy(sizePolicy)
        self.working_folder_change.setObjectName("working_folder_change")
        self.working_folder_layout.addWidget(self.working_folder_change)
        self.main_layout.addLayout(self.working_folder_layout)
        self.server_info_layout = QtWidgets.QHBoxLayout()
        self.server_info_layout.setObjectName("server_info_layout")
        self.server_info = QtWidgets.QLabel(FileServerForm)
        self.server_info.setObjectName("server_info")
        self.server_info_layout.addWidget(self.server_info)
        self.toggle_working = QtWidgets.QPushButton(FileServerForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_working.sizePolicy().hasHeightForWidth())
        self.toggle_working.setSizePolicy(sizePolicy)
        self.toggle_working.setObjectName("toggle_working")
        self.server_info_layout.addWidget(self.toggle_working)
        self.main_layout.addLayout(self.server_info_layout)
        self.no_folder_notice = QtWidgets.QLabel(FileServerForm)
        self.no_folder_notice.setAlignment(QtCore.Qt.AlignCenter)
        self.no_folder_notice.setWordWrap(True)
        self.no_folder_notice.setObjectName("no_folder_notice")
        self.main_layout.addWidget(self.no_folder_notice)

        self.retranslateUi(FileServerForm)
        self.working_folder_change.clicked.connect(FileServerForm.change_working_folder) # type: ignore
        self.toggle_working.clicked.connect(FileServerForm.toggle_server) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FileServerForm)

    def retranslateUi(self, FileServerForm):
        _translate = QtCore.QCoreApplication.translate
        FileServerForm.setWindowTitle(_translate("FileServerForm", "File Server"))
        self.working_folder_label.setText(_translate("FileServerForm", "Target Folder: "))
        self.working_folder_change.setText(_translate("FileServerForm", "Change"))
        self.server_info.setText(_translate("FileServerForm", "Server Status: Stopped"))
        self.toggle_working.setText(_translate("FileServerForm", "Start"))
        self.no_folder_notice.setText(_translate("FileServerForm", "<html><head/><body><p>Folder download is not supported,please consider compressing folders to zipped files.</p></body></html>"))
from Resources import Resources
