# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.setWindowModality(QtCore.Qt.ApplicationModal)
        LoginForm.resize(331, 211)
        LoginForm.setMinimumSize(QtCore.QSize(331, 211))
        LoginForm.setMaximumSize(QtCore.QSize(331, 211))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Resources/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginForm.setWindowIcon(icon)
        self.username = QtWidgets.QLineEdit(LoginForm)
        self.username.setGeometry(QtCore.QRect(120, 61, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(LoginForm)
        self.password.setGeometry(QtCore.QRect(120, 101, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.title = QtWidgets.QLabel(LoginForm)
        self.title.setGeometry(QtCore.QRect(30, 12, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.label_username = QtWidgets.QLabel(LoginForm)
        self.label_username.setGeometry(QtCore.QRect(30, 61, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(LoginForm)
        self.label_password.setGeometry(QtCore.QRect(30, 101, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.login_button = QtWidgets.QPushButton(LoginForm)
        self.login_button.setGeometry(QtCore.QRect(30, 150, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")

        self.retranslateUi(LoginForm)
        self.login_button.clicked.connect(LoginForm.login) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "PYCM Login"))
        self.username.setPlaceholderText(_translate("LoginForm", "Default: admin"))
        self.password.setPlaceholderText(_translate("LoginForm", "Default: 123456"))
        self.title.setText(_translate("LoginForm", "PYCM Login"))
        self.label_username.setText(_translate("LoginForm", "Username:"))
        self.label_password.setText(_translate("LoginForm", "Password:"))
        self.login_button.setText(_translate("LoginForm", "Login"))
        self.login_button.setShortcut(_translate("LoginForm", "Return"))
import Resources_rc
