# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetworkDeviceSelectUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetworkDeviceSelectDialog(object):
    def setupUi(self, NetworkDeviceSelectDialog):
        NetworkDeviceSelectDialog.setObjectName("NetworkDeviceSelectDialog")
        NetworkDeviceSelectDialog.resize(391, 111)
        NetworkDeviceSelectDialog.setMinimumSize(QtCore.QSize(391, 111))
        NetworkDeviceSelectDialog.setMaximumSize(QtCore.QSize(391, 111))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NetworkDeviceSelectDialog.setWindowIcon(icon)
        self.operation_buttons = QtWidgets.QDialogButtonBox(NetworkDeviceSelectDialog)
        self.operation_buttons.setGeometry(QtCore.QRect(10, 60, 371, 41))
        self.operation_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.operation_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.operation_buttons.setCenterButtons(True)
        self.operation_buttons.setObjectName("operation_buttons")
        self.network_device_list = QtWidgets.QComboBox(NetworkDeviceSelectDialog)
        self.network_device_list.setGeometry(QtCore.QRect(20, 20, 351, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.network_device_list.setFont(font)
        self.network_device_list.setObjectName("network_device_list")

        self.retranslateUi(NetworkDeviceSelectDialog)
        self.operation_buttons.accepted.connect(NetworkDeviceSelectDialog.accept) # type: ignore
        self.operation_buttons.rejected.connect(NetworkDeviceSelectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NetworkDeviceSelectDialog)

    def retranslateUi(self, NetworkDeviceSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        NetworkDeviceSelectDialog.setWindowTitle(_translate("NetworkDeviceSelectDialog", "Network Settings"))
from Resources import Resources
