# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteSpyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteSpy(object):
    def setupUi(self, RemoteSpy):
        RemoteSpy.setObjectName("RemoteSpy")
        RemoteSpy.resize(971, 598)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RemoteSpy.sizePolicy().hasHeightForWidth())
        RemoteSpy.setSizePolicy(sizePolicy)
        RemoteSpy.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RemoteSpy.setWindowIcon(icon)
        self.screen_display = QtWidgets.QLabel(RemoteSpy)
        self.screen_display.setGeometry(QtCore.QRect(0, 0, 421, 341))
        self.screen_display.setMouseTracking(True)
        self.screen_display.setText("")
        self.screen_display.setScaledContents(True)
        self.screen_display.setObjectName("screen_display")

        self.retranslateUi(RemoteSpy)
        QtCore.QMetaObject.connectSlotsByName(RemoteSpy)

    def retranslateUi(self, RemoteSpy):
        _translate = QtCore.QCoreApplication.translate
        RemoteSpy.setWindowTitle(_translate("RemoteSpy", "Remote View"))
from Resources import Resources
