# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteControlUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteControl(object):
    def setupUi(self, RemoteControl):
        RemoteControl.setObjectName("RemoteControl")
        RemoteControl.resize(971, 598)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RemoteControl.sizePolicy().hasHeightForWidth())
        RemoteControl.setSizePolicy(sizePolicy)
        RemoteControl.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/UI/Resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RemoteControl.setWindowIcon(icon)
        self.screen_display = QtWidgets.QLabel(RemoteControl)
        self.screen_display.setGeometry(QtCore.QRect(0, 0, 421, 341))
        self.screen_display.setMouseTracking(True)
        self.screen_display.setText("")
        self.screen_display.setScaledContents(True)
        self.screen_display.setObjectName("screen_display")

        self.retranslateUi(RemoteControl)
        QtCore.QMetaObject.connectSlotsByName(RemoteControl)

    def retranslateUi(self, RemoteControl):
        _translate = QtCore.QCoreApplication.translate
        RemoteControl.setWindowTitle(_translate("RemoteControl", "远程控制"))
import Resources_rc
