# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteCommandGroupUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteCommandGroupDialog(object):
    def setupUi(self, RemoteCommandGroupDialog):
        RemoteCommandGroupDialog.setObjectName("RemoteCommandGroupDialog")
        RemoteCommandGroupDialog.resize(335, 275)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RemoteCommandGroupDialog.sizePolicy().hasHeightForWidth())
        RemoteCommandGroupDialog.setSizePolicy(sizePolicy)
        RemoteCommandGroupDialog.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Resources/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RemoteCommandGroupDialog.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(RemoteCommandGroupDialog)
        self.main_layout.setObjectName("main_layout")
        self.command_group = QtWidgets.QGroupBox(RemoteCommandGroupDialog)
        self.command_group.setObjectName("command_group")
        self.command_group_layout = QtWidgets.QHBoxLayout(self.command_group)
        self.command_group_layout.setContentsMargins(11, 11, 11, 11)
        self.command_group_layout.setObjectName("command_group_layout")
        self.command_select = QtWidgets.QListWidget(self.command_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.command_select.setFont(font)
        self.command_select.setObjectName("command_select")
        self.command_group_layout.addWidget(self.command_select)
        self.main_layout.addWidget(self.command_group)
        self.operation_buttons = QtWidgets.QDialogButtonBox(RemoteCommandGroupDialog)
        self.operation_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.operation_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.operation_buttons.setCenterButtons(True)
        self.operation_buttons.setObjectName("operation_buttons")
        self.main_layout.addWidget(self.operation_buttons)
        self.main_layout.setStretch(0, 5)

        self.retranslateUi(RemoteCommandGroupDialog)
        self.operation_buttons.accepted.connect(RemoteCommandGroupDialog.accept) # type: ignore
        self.operation_buttons.rejected.connect(RemoteCommandGroupDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RemoteCommandGroupDialog)

    def retranslateUi(self, RemoteCommandGroupDialog):
        _translate = QtCore.QCoreApplication.translate
        RemoteCommandGroupDialog.setWindowTitle(_translate("RemoteCommandGroupDialog", "Remote Command"))
        self.command_group.setTitle(_translate("RemoteCommandGroupDialog", "Command Select"))
import Resources_rc
