# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteCommandGroupUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteCommandGroupDialog(object):
    def setupUi(self, RemoteCommandGroupDialog):
        RemoteCommandGroupDialog.setObjectName("RemoteCommandGroupDialog")
        RemoteCommandGroupDialog.resize(390, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RemoteCommandGroupDialog.sizePolicy().hasHeightForWidth())
        RemoteCommandGroupDialog.setSizePolicy(sizePolicy)
        RemoteCommandGroupDialog.setMinimumSize(QtCore.QSize(390, 350))
        RemoteCommandGroupDialog.setMaximumSize(QtCore.QSize(390, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RemoteCommandGroupDialog.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(RemoteCommandGroupDialog)
        self.main_layout.setObjectName("main_layout")
        self.command_group = QtWidgets.QGroupBox(RemoteCommandGroupDialog)
        self.command_group.setObjectName("command_group")
        self.command_group_layout = QtWidgets.QHBoxLayout(self.command_group)
        self.command_group_layout.setContentsMargins(11, 11, 11, 11)
        self.command_group_layout.setObjectName("command_group_layout")
        self.command_select = QtWidgets.QListWidget(self.command_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.command_select.setFont(font)
        self.command_select.setObjectName("command_select")
        self.command_group_layout.addWidget(self.command_select)
        self.command_edit_layout = QtWidgets.QVBoxLayout()
        self.command_edit_layout.setObjectName("command_edit_layout")
        self.command_add = QtWidgets.QPushButton(self.command_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_add.sizePolicy().hasHeightForWidth())
        self.command_add.setSizePolicy(sizePolicy)
        self.command_add.setMinimumSize(QtCore.QSize(30, 30))
        self.command_add.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.command_add.setFont(font)
        self.command_add.setText("+")
        self.command_add.setObjectName("command_add")
        self.command_edit_layout.addWidget(self.command_add)
        self.command_remove = QtWidgets.QPushButton(self.command_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_remove.sizePolicy().hasHeightForWidth())
        self.command_remove.setSizePolicy(sizePolicy)
        self.command_remove.setMinimumSize(QtCore.QSize(30, 30))
        self.command_remove.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.command_remove.setFont(font)
        self.command_remove.setText("-")
        self.command_remove.setObjectName("command_remove")
        self.command_edit_layout.addWidget(self.command_remove)
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.command_edit_layout.addItem(spacerItem)
        self.command_group_layout.addLayout(self.command_edit_layout)
        self.command_group_layout.setStretch(0, 10)
        self.command_group_layout.setStretch(1, 1)
        self.main_layout.addWidget(self.command_group)
        self.operation_buttons = QtWidgets.QDialogButtonBox(RemoteCommandGroupDialog)
        self.operation_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.operation_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.operation_buttons.setCenterButtons(True)
        self.operation_buttons.setObjectName("operation_buttons")
        self.main_layout.addWidget(self.operation_buttons)
        self.main_layout.setStretch(0, 5)

        self.retranslateUi(RemoteCommandGroupDialog)
        self.operation_buttons.accepted.connect(RemoteCommandGroupDialog.accept) # type: ignore
        self.operation_buttons.rejected.connect(RemoteCommandGroupDialog.reject) # type: ignore
        self.command_add.clicked.connect(RemoteCommandGroupDialog.add_command) # type: ignore
        self.command_remove.clicked.connect(RemoteCommandGroupDialog.remove_command) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RemoteCommandGroupDialog)

    def retranslateUi(self, RemoteCommandGroupDialog):
        _translate = QtCore.QCoreApplication.translate
        RemoteCommandGroupDialog.setWindowTitle(_translate("RemoteCommandGroupDialog", "Remote Command"))
        self.command_group.setTitle(_translate("RemoteCommandGroupDialog", "Command Select"))
from Resources import Resources
