# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteCommandGroupAddUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteCommandGroupAddDialog(object):
    def setupUi(self, RemoteCommandGroupAddDialog):
        RemoteCommandGroupAddDialog.setObjectName("RemoteCommandGroupAddDialog")
        RemoteCommandGroupAddDialog.resize(343, 284)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RemoteCommandGroupAddDialog.sizePolicy().hasHeightForWidth())
        RemoteCommandGroupAddDialog.setSizePolicy(sizePolicy)
        RemoteCommandGroupAddDialog.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RemoteCommandGroupAddDialog.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(RemoteCommandGroupAddDialog)
        self.main_layout.setObjectName("main_layout")
        self.title_layout = QtWidgets.QHBoxLayout()
        self.title_layout.setObjectName("title_layout")
        self.title_label = QtWidgets.QLabel(RemoteCommandGroupAddDialog)
        self.title_label.setObjectName("title_label")
        self.title_layout.addWidget(self.title_label)
        self.title = QtWidgets.QLineEdit(RemoteCommandGroupAddDialog)
        self.title.setObjectName("title")
        self.title_layout.addWidget(self.title)
        self.main_layout.addLayout(self.title_layout)
        self.command_layout = QtWidgets.QHBoxLayout()
        self.command_layout.setObjectName("command_layout")
        self.command_label = QtWidgets.QLabel(RemoteCommandGroupAddDialog)
        self.command_label.setObjectName("command_label")
        self.command_layout.addWidget(self.command_label)
        self.command = QtWidgets.QPlainTextEdit(RemoteCommandGroupAddDialog)
        self.command.setObjectName("command")
        self.command_layout.addWidget(self.command)
        self.main_layout.addLayout(self.command_layout)
        self.button_box = QtWidgets.QDialogButtonBox(RemoteCommandGroupAddDialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.main_layout.addWidget(self.button_box)

        self.retranslateUi(RemoteCommandGroupAddDialog)
        self.button_box.accepted.connect(RemoteCommandGroupAddDialog.accept) # type: ignore
        self.button_box.rejected.connect(RemoteCommandGroupAddDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RemoteCommandGroupAddDialog)

    def retranslateUi(self, RemoteCommandGroupAddDialog):
        _translate = QtCore.QCoreApplication.translate
        RemoteCommandGroupAddDialog.setWindowTitle(_translate("RemoteCommandGroupAddDialog", "Add Remote Command"))
        self.title_label.setText(_translate("RemoteCommandGroupAddDialog", "Name"))
        self.command_label.setText(_translate("RemoteCommandGroupAddDialog", "Command"))
from Resources import Resources
