# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(487, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Resources/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialog.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(AboutDialog)
        self.main_layout.setContentsMargins(25, 20, 25, 20)
        self.main_layout.setObjectName("main_layout")
        self.title_layout = QtWidgets.QVBoxLayout()
        self.title_layout.setSpacing(0)
        self.title_layout.setObjectName("title_layout")
        self.productName = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.productName.setFont(font)
        self.productName.setAlignment(QtCore.Qt.AlignCenter)
        self.productName.setObjectName("productName")
        self.title_layout.addWidget(self.productName)
        self.buildInfo = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        self.buildInfo.setFont(font)
        self.buildInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.buildInfo.setObjectName("buildInfo")
        self.title_layout.addWidget(self.buildInfo)
        self.label = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.title_layout.addWidget(self.label)
        self.main_layout.addLayout(self.title_layout)
        self.license_group = QtWidgets.QGroupBox(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        self.license_group.setFont(font)
        self.license_group.setAlignment(QtCore.Qt.AlignCenter)
        self.license_group.setObjectName("license_group")
        self.license_group_layout = QtWidgets.QVBoxLayout(self.license_group)
        self.license_group_layout.setObjectName("license_group_layout")
        self.license_view = QtWidgets.QTextBrowser(self.license_group)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        font.setBold(True)
        font.setWeight(75)
        self.license_view.setFont(font)
        self.license_view.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'阿里巴巴普惠体\',\'阿里巴巴普惠体\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400;\">This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or at your option any later version.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:10pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400;\">This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:10pt; font-weight:400;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400;\">You should have received a copy of the GNU General Public License along with this program. If not, see &lt;</span><a href=\"https://www.gnu.org/licenses/\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; text-decoration: underline; color:#0000ff;\">https://www.gnu.org/licenses/</span></a><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400;\">&gt;.</span></p></body></html>")
        self.license_view.setOpenExternalLinks(True)
        self.license_view.setObjectName("license_view")
        self.license_group_layout.addWidget(self.license_view)
        self.main_layout.addWidget(self.license_group)
        self.operation_buttons = QtWidgets.QDialogButtonBox(AboutDialog)
        self.operation_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.operation_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.operation_buttons.setCenterButtons(True)
        self.operation_buttons.setObjectName("operation_buttons")
        self.main_layout.addWidget(self.operation_buttons)

        self.retranslateUi(AboutDialog)
        self.operation_buttons.accepted.connect(AboutDialog.accept) # type: ignore
        self.operation_buttons.rejected.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.productName.setText(_translate("AboutDialog", "PYCM Client"))
        self.buildInfo.setText(_translate("AboutDialog", "No build info"))
        self.label.setText(_translate("AboutDialog", "<html><head/><body><p>Project Home: <a href=\"https://github.com/yangzhongtian001/PYCM\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/yangzhongtian001/PYCM</span></a></p></body></html>"))
        self.license_group.setTitle(_translate("AboutDialog", "GNU General Public License"))
import Resources_rc
