# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientLabelDisplayUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientLabelDisplayForm(object):
    def setupUi(self, ClientLabelDisplayForm):
        ClientLabelDisplayForm.setObjectName("ClientLabelDisplayForm")
        ClientLabelDisplayForm.resize(619, 96)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ClientLabelDisplayForm.setWindowIcon(icon)
        ClientLabelDisplayForm.setStyleSheet("background: transparent;")
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientLabelDisplayForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.client_label = QtWidgets.QLabel(ClientLabelDisplayForm)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.client_label.setFont(font)
        self.client_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.client_label.setStyleSheet("color: rgb(85, 170, 255);")
        self.client_label.setText("c")
        self.client_label.setTextFormat(QtCore.Qt.PlainText)
        self.client_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.client_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.client_label.setObjectName("client_label")
        self.verticalLayout.addWidget(self.client_label)

        self.retranslateUi(ClientLabelDisplayForm)
        QtCore.QMetaObject.connectSlotsByName(ClientLabelDisplayForm)

    def retranslateUi(self, ClientLabelDisplayForm):
        pass
from Resources import Resources
