# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileClient(object):
    def setupUi(self, FileClient):
        FileClient.setObjectName("FileClient")
        FileClient.setWindowModality(QtCore.Qt.ApplicationModal)
        FileClient.resize(492, 336)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Resources/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FileClient.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(FileClient)
        self.main_layout.setObjectName("main_layout")
        self.file_area_container = QtWidgets.QVBoxLayout()
        self.file_area_container.setObjectName("file_area_container")
        self.file_area = QtWidgets.QListWidget(FileClient)
        self.file_area.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_area.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.file_area.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.file_area.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.file_area.setGridSize(QtCore.QSize(100, 100))
        self.file_area.setViewMode(QtWidgets.QListView.IconMode)
        self.file_area.setUniformItemSizes(True)
        self.file_area.setWordWrap(True)
        self.file_area.setObjectName("file_area")
        self.file_area_container.addWidget(self.file_area)
        self.download_button = QtWidgets.QPushButton(FileClient)
        self.download_button.setEnabled(False)
        self.download_button.setObjectName("download_button")
        self.file_area_container.addWidget(self.download_button)
        self.download_progress = QtWidgets.QProgressBar(FileClient)
        self.download_progress.setProperty("value", 0)
        self.download_progress.setObjectName("download_progress")
        self.file_area_container.addWidget(self.download_progress)
        self.main_layout.addLayout(self.file_area_container)
        self.main_layout.setStretch(0, 1)

        self.retranslateUi(FileClient)
        self.download_button.clicked.connect(FileClient.download) # type: ignore
        self.file_area.itemSelectionChanged.connect(FileClient.update_selection) # type: ignore
        self.file_area.itemDoubleClicked['QListWidgetItem*'].connect(FileClient.switch_dir) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FileClient)

    def retranslateUi(self, FileClient):
        _translate = QtCore.QCoreApplication.translate
        FileClient.setWindowTitle(_translate("FileClient", "File Client"))
        self.download_button.setText(_translate("FileClient", "Download"))
import Resources_rc
