# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(397, 54)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainForm.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(MainForm)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.main_container = QtWidgets.QWidget(MainForm)
        self.main_container.setObjectName("main_container")
        self.main_container_layout = QtWidgets.QVBoxLayout(self.main_container)
        self.main_container_layout.setContentsMargins(0, 0, 0, 0)
        self.main_container_layout.setSpacing(0)
        self.main_container_layout.setObjectName("main_container_layout")
        self.title_label = QtWidgets.QLabel(self.main_container)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(82, 229, 231, 255), stop:1 rgba(19, 12, 183, 255));\n"
"color: rgb(255, 255, 255);")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.main_container_layout.addWidget(self.title_label)
        self.tool_buttons_layout = QtWidgets.QHBoxLayout()
        self.tool_buttons_layout.setContentsMargins(5, 3, 5, 5)
        self.tool_buttons_layout.setSpacing(5)
        self.tool_buttons_layout.setObjectName("tool_buttons_layout")
        self.notify_button = QtWidgets.QPushButton(self.main_container)
        self.notify_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notify_button.sizePolicy().hasHeightForWidth())
        self.notify_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.notify_button.setFont(font)
        self.notify_button.setObjectName("notify_button")
        self.tool_buttons_layout.addWidget(self.notify_button)
        self.file_button = QtWidgets.QPushButton(self.main_container)
        self.file_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_button.sizePolicy().hasHeightForWidth())
        self.file_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.file_button.setFont(font)
        self.file_button.setObjectName("file_button")
        self.tool_buttons_layout.addWidget(self.file_button)
        self.private_message_button = QtWidgets.QPushButton(self.main_container)
        self.private_message_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.private_message_button.sizePolicy().hasHeightForWidth())
        self.private_message_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.private_message_button.setFont(font)
        self.private_message_button.setObjectName("private_message_button")
        self.tool_buttons_layout.addWidget(self.private_message_button)
        self.hide_button = QtWidgets.QPushButton(self.main_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_button.sizePolicy().hasHeightForWidth())
        self.hide_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hide_button.setFont(font)
        self.hide_button.setObjectName("hide_button")
        self.tool_buttons_layout.addWidget(self.hide_button)
        self.tool_buttons_layout.setStretch(0, 1)
        self.tool_buttons_layout.setStretch(1, 1)
        self.tool_buttons_layout.setStretch(2, 1)
        self.tool_buttons_layout.setStretch(3, 1)
        self.main_container_layout.addLayout(self.tool_buttons_layout)
        self.main_layout.addWidget(self.main_container)
        self.action_send_file = QtWidgets.QAction(MainForm)
        self.action_send_file.setObjectName("action_send_file")
        self.action_file_client = QtWidgets.QAction(MainForm)
        self.action_file_client.setObjectName("action_file_client")

        self.retranslateUi(MainForm)
        self.notify_button.clicked.connect(MainForm.notify_console) # type: ignore
        self.hide_button.clicked.connect(MainForm.hide) # type: ignore
        self.private_message_button.clicked.connect(MainForm.show_messaging_window) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Client"))
        self.title_label.setText(_translate("MainForm", "PYCM Client - Offline"))
        self.notify_button.setText(_translate("MainForm", "Hands Up"))
        self.file_button.setText(_translate("MainForm", "File"))
        self.private_message_button.setText(_translate("MainForm", "Messaging"))
        self.hide_button.setText(_translate("MainForm", "Hide"))
        self.action_send_file.setText(_translate("MainForm", "Send File"))
        self.action_file_client.setText(_translate("MainForm", "File Client"))
from Resources import Resources
